# Generated by Django 5.0 on 2025-12-24 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("candidates", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("company", models.CharField(max_length=255)),
                ("description", models.TextField(help_text="Raw job description text")),
                (
                    "competencies",
                    models.JSONField(
                        default=dict, help_text="Parsed competencies from LLM"
                    ),
                ),
                (
                    "required_skills",
                    models.JSONField(
                        default=list, help_text="Required skills extracted from JD"
                    ),
                ),
                (
                    "optional_skills",
                    models.JSONField(
                        default=list, help_text="Optional/nice-to-have skills"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("CLOSED", "Closed")],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("posted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recruiter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_descriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Description",
                "verbose_name_plural": "Job Descriptions",
                "db_table": "job_descriptions",
                "ordering": ["-posted_at"],
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resume_id",
                    models.CharField(
                        help_text="UUID of the generated resume", max_length=100
                    ),
                ),
                (
                    "resume_version",
                    models.JSONField(
                        help_text="Snapshot of candidate data used in resume"
                    ),
                ),
                (
                    "generated_pdf_path",
                    models.CharField(
                        help_text="Path to generated PDF file", max_length=500
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("SHORTLISTED", "Shortlisted"),
                            ("REJECTED", "Rejected"),
                            ("INTERVIEWED", "Interviewed"),
                            ("HIRED", "Hired"),
                        ],
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                (
                    "match_explanation",
                    models.JSONField(
                        default=dict,
                        help_text="LLM-generated explanation of why candidate matched",
                    ),
                ),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="candidates.candidateprofile",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="recruiters.jobdescription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Application",
                "verbose_name_plural": "Applications",
                "db_table": "applications",
                "ordering": ["-applied_at"],
                "unique_together": {("candidate", "job")},
            },
        ),
        migrations.CreateModel(
            name="RecruiterFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("SHORTLIST", "Shortlist"),
                            ("REJECT", "Reject"),
                            ("INTERVIEW", "Interview"),
                            ("HIRE", "Hire"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Optional reason for the action"
                    ),
                ),
                (
                    "feedback_data",
                    models.JSONField(
                        default=dict,
                        help_text="Structured data for graph weight updates",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="recruiters.application",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recruiter Feedback",
                "verbose_name_plural": "Recruiter Feedbacks",
                "db_table": "recruiter_feedbacks",
                "ordering": ["-created_at"],
            },
        ),
    ]
