# Generated by Django 5.0 on 2025-12-30 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0003_candidateprofile_custom_links_and_more"),
        ("recruiters", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationPreview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("match_strength", models.FloatField(default=0.0)),
                ("required_coverage", models.CharField(blank=True, max_length=32)),
                ("selected_projects", models.PositiveIntegerField(default=0)),
                ("selected_skills", models.PositiveIntegerField(default=0)),
                ("selected_content", models.JSONField(default=dict)),
                ("coverage_summary", models.JSONField(blank=True, default=dict)),
                ("candidate_updated_at", models.DateTimeField()),
                ("job_updated_at", models.DateTimeField()),
                ("computed_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_previews",
                        to="candidates.candidateprofile",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_previews",
                        to="recruiters.jobdescription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Application Preview",
                "verbose_name_plural": "Application Previews",
                "db_table": "application_previews",
                "ordering": ["-computed_at"],
                "unique_together": {("candidate", "job")},
            },
        ),
    ]
