# Generated by Django 5.0 on 2026-03-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruiters", "0002_applicationpreview"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="interview_questions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="LLM-generated interview questions for shortlisted candidates",
            ),
        ),
    ]
