# Generated by Django 5.0 on 2025-12-25 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateprofile",
            name="awards",
            field=models.JSONField(
                default=list,
                help_text="List of awards/achievements: [{title, organization, level, date}]",
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="education",
            field=models.JSONField(
                default=list,
                help_text="List of education entries: [{degree, institution, start_year, end_year, cgpa}]",
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="experience",
            field=models.JSONField(
                default=list,
                help_text="List of work experiences: [{company, role, start_date, end_date, responsibilities: []}]",
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="extracurricular",
            field=models.JSONField(
                default=list,
                help_text="List of extracurricular activities: [{role, organization, location, description}]",
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="github",
            field=models.URLField(
                blank=True, help_text="GitHub profile URL", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="linkedin",
            field=models.URLField(
                blank=True, help_text="LinkedIn profile URL", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="publications",
            field=models.JSONField(
                default=list,
                help_text="List of publications: [{title, venue, date, doi, description}]",
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="summary",
            field=models.TextField(
                blank=True, help_text="Professional summary (2-3 sentences)"
            ),
        ),
    ]
