# Generated by Django 5.0 on 2025-12-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "candidates",
            "0002_candidateprofile_awards_candidateprofile_education_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateprofile",
            name="custom_links",
            field=models.JSONField(
                default=list,
                help_text="List of custom links: [{label, url, description}]",
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="patents",
            field=models.JSONField(
                default=list,
                help_text="List of patents: [{title, patent_number, filing_date, grant_date, description, inventors}]",
            ),
        ),
    ]
