# Generated by Django 5.0 on 2026-03-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0003_candidateprofile_custom_links_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("url", models.URLField(max_length=2000)),
                ("category", models.CharField(max_length=300)),
                ("source", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Learning Resource",
                "verbose_name_plural": "Learning Resources",
                "db_table": "learning_resources",
                "ordering": ["category", "title"],
                "unique_together": {("url", "source")},
            },
        ),
    ]
