# Generated by ChatGPT on 2025-12-25
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('recruiters', '0001_initial'),
        ('candidates', '0003_candidateprofile_custom_links_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_id', models.CharField(max_length=64, unique=True)),
                ('base_label', models.CharField(max_length=255)),
                ('base_slug', models.CharField(max_length=255)),
                ('display_label', models.CharField(max_length=255)),
                ('version', models.PositiveIntegerField(default=1)),
                ('jd_title', models.CharField(blank=True, max_length=255)),
                ('jd_company', models.CharField(blank=True, max_length=255)),
                ('pdf_path', models.CharField(max_length=500)),
                ('source', models.CharField(choices=[('JOB', 'Job'), ('JD_TEXT', 'Job Description Text')], max_length=10)),
                ('jd_snapshot', models.JSONField(blank=True, default=dict)),
                ('graph_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_resumes', to='candidates.candidateprofile')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_resumes', to='recruiters.jobdescription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='generatedresume',
            index=models.Index(fields=['candidate', 'base_slug'], name='resume_eng_candida_5f4216_idx'),
        ),
    ]
