# Generated by Django 5.0 on 2025-12-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LLMUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("api_key_fingerprint", models.CharField(max_length=64)),
                ("date", models.DateField()),
                ("count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["model_name", "date"],
                        name="llm_service_model_n_ec61ee_idx",
                    ),
                    models.Index(
                        fields=["api_key_fingerprint", "date"],
                        name="llm_service_api_key_c1503c_idx",
                    ),
                ],
                "unique_together": {("model_name", "api_key_fingerprint", "date")},
            },
        ),
    ]
